### ISSUE TITLE
Two PRs green apart can break main together, and nothing in the pipeline looks

### ISSUE THREAD

**Issue by misnaej** [misnaej/forge#524]
Requires: nothing

## What happened

On 2026-09-09, PRs #517 and #521 were each green on their own branch and merged within two minutes of each other. Main then failed fourteen tests with `TypeError: _run_hook() got an unexpected keyword argument 'agent_type'`.

Neither PR was wrong. #517 replaced the keyword parameters of `tests/test_claude_hooks.py`'s shared `_run_hook` / `_run_hook_proc` helpers with a `HookOptions` object and converted every call site that existed on its branch. #521, developed in parallel, added tests written against the signature that was still current on *its* branch. Each branch contained only its own change, so both suites passed. The two edits touched different lines of the same file, so git merged them without reporting a conflict, and the result compiled into calls that no longer match the helper.

This is a semantic conflict: correct on both sides, broken in the union, invisible to every gate we run.

## Why nothing caught it

- Branch CI tests the branch, not the merge result.
- `git merge` reports textual conflicts only.
- The base-sync gate in `/pr` Step 0.5 asks whether the branch is behind and whether it conflicts. Both answers were reassuring: #521 had merged main at 09dff02, before #517 landed, and nothing conflicted afterwards.
- The `warn_stale_wrapup` hook and the PR monitor watch the wrap-up's SHA and the merge state, not whether the base moved under a green branch.

## Request

Investigate what forge can offer here, and pick one — this is a spike, not a prescribed fix:

1. **Test the merge, not the branch.** A CI job on `pull_request` already runs against a merge commit on GitHub; check whether forge's workflow uses `github.event.pull_request.merge_commit_sha` or the branch head, and switch if it is the latter. This alone would have caught it.
2. **Re-verify on base movement.** When main moves while a PR is open and mergeable, the monitor could re-run the change-scoped suite against the merge result and alert, in the same shape as the existing staleness warning.
3. **Sequence the merge.** A PR whose base moved since its last verification is not merge-ready until it merges the base and its checks run again; that is a rule, and a rule needs a gate to be worth writing.

Note the fix for the incident itself is #523, not this issue. This issue is about the class.

Bump: to be decided by the approach.

**Comment by misnaej** [comment]
[issue-triage] tier-2-high applied, `research` added (spike, not a prescribed fix): a real incident today — two independently-green PRs merged a semantic conflict into main, invisible to every existing gate. High ROI, recent, and the class recurs until addressed, so high rather than standard; not tier-1 since the incident itself is already resolved by #523 and this issue tracks prevention, not an active break. `Requires: nothing` confirmed.

forge-internal judgement: NOT forge-internal. The issue was triggered by forge's own CI/PR pipeline, but all three proposed approaches (testing the actual merge commit in CI, re-verifying on base movement, or sequencing merges before merge-readiness) are pipeline/gate machinery that would ship to consumers as a hook, CI recipe, or forge CLI — same class as `warn_stale_wrapup` / the PR monitor. Primary deliverable is shipped surface, so the label is withheld.

**Comment by ingmarschuster** [comment]
[issue-triage] forge-internal left unset: balanced — the incident is in forge's own CI, but the proposed fix is mostly the shipped /pr gate and PR monitor.
